# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41e17ee7ac1244f1af6d3704cc2bcefbdf8017ecfe1c9add230a9871b9f08b6db5d46c951b1867fa520dfb3a8638e1722ae660a4700c616982eaa6ea550f2f35

test:
  secret_key_base: c8e0a07406df3997c9ff14221097e2ffab990966fe2f0a8bf86c22b9db84784bbdb49fdc54ddaa79af84ed53a7d9d102058add1616ae254fc7e2802e9a34ee92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
